import { defineConfig } from 'astro/config';
import icon from 'astro-icon';
import sitemap from '@astrojs/sitemap';
import { fileURLToPath } from 'node:url';

const srcDir = fileURLToPath(new URL('./src', import.meta.url));

export default defineConfig({
  site: 'https://auxodata.com',
  prefetch: {
    defaultStrategy: 'viewport',
  },
  vite: {
    build: {
      target: 'esnext',
      rollupOptions: {
        output: {
          manualChunks(id) {
            if (id.includes('node_modules')) {
              if (id.includes('embla-carousel')) return 'ui-vendor';
              if (id.includes('astro-icon') || id.includes('@iconify')) return 'icons';
              if (id.includes('@emailjs')) return 'emailjs';
            }
          },
        },
      },
    },
    esbuild: {
      legalComments: 'none',
    },
    logLevel: 'warn',
    resolve: { alias: { '@': srcDir } },
  },
  integrations: [
    sitemap({
      changefreq: 'weekly',
      priority: 0.7,
      lastmod: new Date(),
      i18n: {
        defaultLocale: 'en',
        locales: {
          en: 'en-US',
        },
      },
    }),
    icon({
      include: {
        'simple-icons': [
          'python',
          'amazonaws',
          'microsoftazure',
          'googlecloud',
          'snowflake',
          'databricks',
          'tableau',
          'powerbi',
          'dbt',
          'apacheairflow',
          'apachespark',
          'apachekafka',
          'tensorflow',
          'pytorch',
          'postgresql',
          'mongodb',
          'docker',
          'kubernetes',
        ],
        mdi: [
          'ab-testing',
          'account-cog-outline',
          'account-group',
          'account-group-outline',
          'account-switch-outline',
          'account-tie',
          'account-network',
          'alarm-light-outline',
          'alert-circle',
          'alert-circle-outline',
          'alert-decagram-outline',
          'arrow-left',
          'arrow-right',
          'atom',
          'auto-fix',
          'file-tree',
          'book-open',
          'book-open-variant',
          'book-open-variant-outline',
          'brain',
          'briefcase',
          'briefcase-clock-outline',
          'briefcase-outline',
          'bullseye',
          'calendar-check-outline',
          'calendar-clock',
          'calendar-clock-outline',
          'calendar-outline',
          'cart',
          'cash-fast',
          'cellphone-cog',
          'chart-areaspline',
          'chart-box',
          'chart-box-multiple-outline',
          'chart-box-outline',
          'chart-donut-variant',
          'chart-line',
          'chart-line-variant',
          'chart-timeline-variant',
          'check-bold',
          'check-circle',
          'check-circle-outline',
          'check-decagram',
          'check-decagram-outline',
          'checkbox-marked',
          'chevron-down',
          'clipboard-check-outline',
          'clipboard-list',
          'clipboard-list-outline',
          'clipboard-text-clock-outline',
          'clipboard-text-outline',
          'clock-check-outline',
          'clock-outline',
          'close',
          'close-circle-outline',
          'cog-play',
          'cog-sync',
          'cog-transfer-outline',
          'cogs',
          'compass-outline',
          'cookie',
          'crosshairs-gps',
          'crystal-ball',
          'database-arrow-right-outline',
          'database-check-outline',
          'database-cog',
          'database-plus',
          'database-search',
          'domain',
          'earth',
          'email-outline',
          'eye-check-outline',
          'file-chart',
          'file-chart-outline',
          'file-document',
          'file-document-multiple',
          'file-document-multiple-outline',
          'file-document-outline',
          'file-search-outline',
          'file-send',
          'file-tree',
          'finance',
          'filter-check-outline',
          'flag-checkered',
          'flash-outline',
          'format-list-bulleted',
          'format-list-checks',
          'function-variant',
          'gavel',
          'graph-outline',
          'hammer-wrench',
          'handshake',
          'head-lightbulb',
          'home',
          'human-greeting-variant',
          'information-outline',
          'layers',
          'lightbulb',
          'lightbulb-on',
          'lightbulb-on-outline',
          'linkedin',
          'lock-check-outline',
          'magnify-scan',
          'map-marker',
          'map-marker-outline',
          'map-marker-path',
          'map-search',
          'map-search-outline',
          'monitor-dashboard',
          'monitor-eye',
          'moon-waning-crescent',
          'minus',
          'note-edit',
          'package-variant',
          'palette',
          'palm-tree',
          'pipe',
          'playlist-check',
          'plus',
          'quality-high',
          'radar',
          'refresh-circle',
          'relation-many-to-many',
          'robot',
          'robot-outline',
          'rocket-launch',
          'rocket-launch-outline',
          'rocket-outline',
          'run-fast',
          'scale-balance',
          'school',
          'school-outline',
          'send',
          'server-network',
          'shield-account',
          'shield-account-outline',
          'shield-alert-outline',
          'shield-check',
          'shield-check-outline',
          'shield-lock',
          'shield-search',
          'shield-star',
          'shield-sync-outline',
          'shopping',
          'source-branch-check',
          'speedometer-medium',
          'star-circle',
          'telescope',
          'text-recognition',
          'timeline-clock-outline',
          'timer-outline',
          'toolbox',
          'trending-up',
          'tune',
          'tune-variant',
          'twitter',
          'vector-arrange-above',
          'vector-difference-ab',
          'vector-polyline-plus',
          'view-dashboard-outline',
          'view-dashboard-variant',
          'waves',
          'web',
          'white-balance-sunny',
        ],
      },
    }),
  ],
});
