import { defineConfig } from 'astro/config';
import icon from 'astro-icon';
import sitemap from '@astrojs/sitemap';
import mdx from '@astrojs/mdx';
import partytown from '@astrojs/partytown';
import pagefind from 'astro-pagefind';
import vercel from '@astrojs/vercel';
import { unified } from '@astrojs/markdown-remark';
import { fileURLToPath } from 'node:url';
import { remarkReadingTime } from './src/lib/remark-reading-time.mjs';

const srcDir = fileURLToPath(new URL('./src', import.meta.url));

const isPages = process.env.GITHUB_PAGES === 'true';

export default defineConfig({
  site: isPages ? 'https://admin-auxo.github.io' : 'https://auxodata.com',
  base: isPages ? '/auxo-data-labs-site' : undefined,
  ...(isPages ? {} : { adapter: vercel({ webAnalytics: { enabled: false } }) }),
  devToolbar: { enabled: false },
  redirects: {
    '/self-check/': '/services/',
    '/diagnostic/': '/services/',
    '/trust/': '/about/',
    '/blog/': '/',
    '/services/compliance-intelligence/': '/services/',
    '/services/data-spine/': '/services/',
    '/services/portfolio-command/': '/services/',
    '/services/applied-ai/': '/services/',
    '/services/forecast-engine/': '/services/',
    '/services/ops-autopilot/': '/services/',
    '/services/agent-studio/': '/services/',
  },
  prefetch: {
    defaultStrategy: 'viewport',
  },
  markdown: {
    processor: unified({ remarkPlugins: [remarkReadingTime] }),
  },
  vite: {
    build: {
      target: 'esnext',
    },
    esbuild: {
      legalComments: 'none',
    },
    logLevel: 'warn',
    resolve: { alias: { '@': srcDir } },
  },
  integrations: [
    sitemap({
      changefreq: 'weekly',
      priority: 0.7,
      lastmod: new Date(),
      i18n: {
        defaultLocale: 'en',
        locales: {
          en: 'en-US',
        },
      },
    }),
    icon({
      include: {
        'simple-icons': [
          'python',
          'amazonaws',
          'microsoftazure',
          'googlecloud',
          'snowflake',
          'databricks',
          'tableau',
          'powerbi',
          'dbt',
          'apacheairflow',
          'apachespark',
          'apachekafka',
          'tensorflow',
          'pytorch',
          'postgresql',
          'mongodb',
          'docker',
          'kubernetes',
          'x',
        ],
        mdi: [
          'account-check-outline',
          'account-cog-outline',
          'account-group-outline',
          'account-search-outline',
          'account-switch-outline',
          'account-sync-outline',
          'alarm-light-outline',
          'alert-circle-outline',
          'alert-decagram-outline',
          'arrow-left',
          'arrow-right',
          'arrow-up',
          'bank-outline',
          'book-open',
          'brain',
          'briefcase-clock-outline',
          'briefcase-outline',
          'bullhorn-outline',
          'calendar-check-outline',
          'calendar-clock-outline',
          'calendar-outline',
          'chart-areaspline',
          'chart-box-multiple-outline',
          'chart-box-outline',
          'chart-line',
          'chart-timeline-variant',
          'check',
          'check-circle-outline',
          'check-decagram',
          'check-decagram-outline',
          'chevron-down',
          'city-variant-outline',
          'clipboard-check-outline',
          'clock-check-outline',
          'clock-outline',
          'close',
          'close-circle-outline',
          'cog-sync',
          'cog-transfer-outline',
          'compass-outline',
          'connection',
          'cookie',
          'crystal-ball',
          'cube-outline',
          'database-check-outline',
          'database-cog',
          'database-search',
          'domain',
          'email-outline',
          'eye-off-outline',
          'file-chart-outline',
          'file-document',
          'file-document-check-outline',
          'file-document-multiple-outline',
          'file-document-outline',
          'file-sign',
          'file-tree',
          'filter-check-outline',
          'finance',
          'gavel',
          'graph-outline',
          'handshake',
          'home-city-outline',
          'home-percent-outline',
          'hub-outline',
          'key-outline',
          'leaf',
          'lightbulb-on-outline',
          'linkedin',
          'lock-check-outline',
          'lock-outline',
          'magnify',
          'magnify-scan',
          'map-marker-outline',
          'map-marker-path',
          'moon-waning-crescent',
          'office-building-outline',
          'palm-tree',
          'presentation',
          'refresh-circle',
          'robot-happy-outline',
          'robot-outline',
          'rocket-launch',
          'rocket-launch-outline',
          'rocket-outline',
          'scale-balance',
          'school-outline',
          'send',
          'shield-alert-outline',
          'shield-check',
          'shield-check-outline',
          'shield-lock-outline',
          'shield-search',
          'sitemap-outline',
          'source-branch-check',
          'text-box-search-outline',
          'timeline-clock-outline',
          'timer-outline',
          'tune',
          'tune-variant',
          'twitter',
          'vector-arrange-above',
          'vector-polyline-plus',
          'view-dashboard-outline',
          'white-balance-sunny',
        ],
      },
    }),
    mdx(),
    partytown({ config: { forward: ['dataLayer.push'] } }),
    pagefind(),
  ],
});
